; File generated by rgbasm

; Numeric constants
def constant equ $1
def con2 equ $ffffffff

; Variables
def variable = $3
def var2 = $9

; String constants
def string equs "goodbye~"
def str2 equs "hello!\0\n\t\r\\\"\{"

; Character maps
newcharmap main
charmap "c", $4
charmap "c2", $a, $fffffff5, $3ade68b1
newcharmap map2
charmap "c", $4
charmap "c2", $a, $fffffff5, $3ade68b1
charmap "\0\n\t\r", $9, $d, $0, $a

; Macros
macro mac2
	!?@#;^&
endm
