blank_issues_enabled: false
contact_links:
  - name: GBDev Discord
    url: https://discord.gg/RjJKA8wrD4
    about: If you have questions about the RGBDS code or its organization, join our Discord server!
