/*
 * This file is part of RGBDS.
 *
 * Copyright (c) 1997-2018, Carsten Sorensen and RGBDS contributors.
 *
 * SPDX-License-Identifier: MIT
 */

#ifndef RGBDS_COMMON_H
#define RGBDS_COMMON_H

#define RGBDS_OBJECT_VERSION_STRING "RGB6"

enum eBankCount {
	BANK_COUNT_ROM0  = 1,
	BANK_COUNT_ROMX  = 511,
	BANK_COUNT_WRAM0 = 1,
	BANK_COUNT_WRAMX = 7,
	BANK_COUNT_VRAM  = 2,
	BANK_COUNT_OAM   = 1,
	BANK_COUNT_HRAM  = 1,
	BANK_COUNT_SRAM  = 16
};

enum eBankGBCount {
	BANK_MIN_ROM0  = 0,
	BANK_MAX_ROM0  = BANK_COUNT_ROM0  + BANK_MIN_ROM0  - 1,
	BANK_MIN_ROMX  = 1,
	BANK_MAX_ROMX  = BANK_COUNT_ROMX  + BANK_MIN_ROMX  - 1,
	BANK_MIN_WRAM0 = 0,
	BANK_MAX_WRAM0 = BANK_COUNT_WRAM0 + BANK_MIN_WRAM0 - 1,
	BANK_MIN_WRAMX = 1,
	BANK_MAX_WRAMX = BANK_COUNT_WRAMX + BANK_MIN_WRAMX - 1,
	BANK_MIN_VRAM  = 0,
	BANK_MAX_VRAM  = BANK_COUNT_VRAM  + BANK_MIN_VRAM  - 1,
	BANK_MIN_OAM   = 0,
	BANK_MAX_OAM   = BANK_COUNT_OAM   + BANK_MIN_OAM   - 1,
	BANK_MIN_HRAM  = 0,
	BANK_MAX_HRAM  = BANK_COUNT_HRAM  + BANK_MIN_HRAM  - 1,
	BANK_MIN_SRAM  = 0,
	BANK_MAX_SRAM  = BANK_COUNT_SRAM  + BANK_MIN_SRAM  - 1
};

#endif /* RGBDS_COMMON_H */
