.ERASE
.EXTENSIONS:
.EXTENSIONS:	.obj	.c	.l	.y	.h

!include	..\MAKEINIT

!ifeq	TARGET	DOS
EXE	=	rgbasm.exe
!endif
!ifeq	TARGET	WIN95
EXE	=	rgbasm95.exe
!endif

TARGET_SYSTEM	=	GAMEBOY

!include	..\STDMAKE


