name: Static analysis
on:
  - push
  - pull_request

jobs:
  analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install deps
        shell: bash
        run: |
          ./.github/scripts/install_deps.sh ubuntu-latest
      - name: Static analysis
        run: | # Silence warnings with too many false positives (https://stackoverflow.com/a/73913076)
          make -kj CXX=g++-14 CXXFLAGS="-fanalyzer -fanalyzer-verbosity=0 -Wno-analyzer-use-of-uninitialized-value -DNDEBUG" Q=
