name: Code coverage checking
on: pull_request

jobs:
  checkdiff:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Set up repo
        run: |
          git clone -b "${{ github.event.pull_request.head.ref }}" "${{ github.event.pull_request.head.repo.clone_url }}" rgbds
          cd rgbds
          git remote add upstream "${{ github.event.pull_request.base.repo.clone_url }}"
          git fetch upstream
      - name: Checkdiff
        id: checkdiff
        working-directory: rgbds
        run: |
          make checkdiff "BASE_REF=${{ github.event.pull_request.base.sha }}" | tee log
      - name: Comment
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `**Checkdiff:** <pre><code>${{steps.checkdiff.outputs.response}}</code></pre>`
            })
