name: Code format checking
on: pull_request

env:
  # Force colored output (see https://bixense.com/clicolors/ and https://force-color.org/)
  TERM: xterm-256color
  CLICOLOR: 1
  CLICOLOR_FORCE: 1

jobs:
  checkformat:
    runs-on: ubuntu-slim
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
      - name: Check format
        run: |
          contrib/checkformat.bash
