name: Code format checking
on: pull_request

jobs:
  checkformat:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Check format
        run: |
          contrib/checkformat.bash
