name: Code coverage report
on:
  - push
  - pull_request

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
      - name: Install deps
        run: |
          bash .github/scripts/install_deps.sh ubuntu-latest lcov
      - name: Install test dependency dependencies
        run: |
          test/fetch-test-deps.sh --get-deps ubuntu
      - name: Generate coverage report
        run: |
          contrib/coverage.bash ubuntu-ci
      - name: Upload coverage report
        uses: actions/upload-artifact@v7
        with:
          name: coverage-report
          # Workaround for keeping the top-level coverage/ directory
          # https://github.com/actions/upload-artifact/issues/174
          path: |
            coverage
            dummy-file-to-keep-directory-structure.txt
          if-no-files-found: error
