name: Create release docs
on:
  release:
    types:
      - released # This avoids triggering on pre-releases

env:
  # Force colored output (see https://bixense.com/clicolors/ and https://force-color.org/)
  TERM: xterm-256color
  FORCE_COLOR: 1
  CLICOLOR: 1
  CLICOLOR_FORCE: 1

jobs:
  build:
    if: github.repository_owner == 'gbdev'
    runs-on: ubuntu-slim
    steps:
      - name: Checkout rgbds@release
        uses: actions/checkout@v6
        with:
          path: rgbds
          sparse-checkout: man # Avoid checking out other files, we don't use them here.
      - name: Checkout rgbds-www
        uses: actions/checkout@v6
        with:
          path: rgbds-www
          repository: ${{ github.repository_owner }}/rgbds-www
          ref: master # Need to check out the branch to be able to commit on and push it.
          ssh-key: !!str ${{ secrets.SSH_KEY_SECRET }}
      - name: Install groff and mandoc
        run: |
          sudo apt install -Uyq groff mandoc -o APT::Color=yes -o Acquire::Queue-Mode
      - name: Update pages
        working-directory: rgbds/man
        run: | # The ref appears to be in the format "refs/tags/<version>", so strip that
          ../../rgbds-www/maintainer/man_to_html.sh ${GITHUB_REF##*/} *
          ../../rgbds-www/maintainer/new_release.sh ${GITHUB_REF##*/}
      - name: Push new pages
        working-directory: rgbds-www
        env:
          GIT_AUTHOR_NAME: !!str ${{ github.actor }}
          GIT_AUTHOR_EMAIL: !!str ${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com
          GIT_COMMITTER_NAME: github-actions[bot]
          GIT_COMMITTER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
        run: |
          git add -A
          git commit -m "Create RGBDS ${GITHUB_REF##*/} documentation"
          git push
